
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-9.5.15-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |-
    image:
      registry: docker.io
      repository: bitnami/nginx
    metrics:
      enabled: true
